name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  PEXRC_INSTALL_TOOLS: 1

concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

jobs:
  setup:
    name: Check GitHub Organization
    if: github.repository_owner == 'pex-tool'
    runs-on: ubuntu-slim
    steps:
      - name: Noop
        if: false
        run: echo "This is a dummy step that will never run."

  checks:
    name: "Check Formatting and Lints"
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Check Formatting, Lints and Cross-build
        run: |
          rustup toolchain add nightly -c rustfmt
          cargo +nightly fmt --check --all
          cargo --color always clippy --locked --all

  setup-cross-build:
    name: "Determine Cross-build Targets"
    runs-on: ubuntu-24.04-arm
    needs: setup
    outputs:
      targets: ${{ steps.determine-targets.outputs.targets }}
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Determine Targets
        run: |
          cargo --color always build --release -p package
          target/release/package --print-targets json >> "$GITHUB_OUTPUT"
      - name: Upload package binary
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: |
            target/release/package
            .gitignore

  cross-build:
    name: "Cross-build pexrc"
    needs: setup-cross-build
    runs-on: ubuntu-24.04-arm
    # N.B.: We break these up just to save wall time; they all can be built on 1 machine in ~40
    # minutes; this gets us to a ~12 minute long-pole.
    strategy:
      matrix:
        target: ${{ fromJSON(needs.setup-cross-build.outputs.targets) }}
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Download package binary
        uses: actions/download-artifact@v7
        with:
          name: package
      - name: Build pexrc binary for all targets.
        run: |
          target/release/package \
            --color always --profile release -o dist --target ${{ matrix.target }}
      - name: Generate Release Hashes Manifest.
        run: uv run dev-cmd --color always generate-release-hashes -- -i dist

  tests:
    name: "${{ matrix.name }} tests"
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # N.B.: macos-14 is the oldest non-deprecated ARM Mac runner.
        include:
          - name: Linux aarch64
            os: ubuntu-22.04-arm
          - name: Linux x86_64
            os: ubuntu-22.04
          - name: Mac aarch64
            os: macos-14
          - name: Mac x86_64
            os: macos-x86_64
          - name: Windows aarch64
            os: windows-11-arm
          - name: Windows x86_64
            os: windows-2022
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Run Tests
        run: |
          cargo --color always test --all
          PEXRC_PROFILE=release uv run dev-cmd --color always test -- -vvs

  final-status:
    name: Gather Final Status
    needs:
      - checks
      - cross-build
      - tests
    runs-on: ubuntu-slim
    steps:
      - name: Check Non-Success
        if: |
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'skipped')
        run: "false"
      - name: Success
        run: "true"
