name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to manually run a deploy for.
        required: true
defaults:
  run:
    shell: bash
env:
  PEXRC_INSTALL_TOOLS: 1

jobs:
  setup:
    name: Check GitHub Organization
    if: github.repository_owner == 'pex-tool'
    runs-on: ubuntu-slim
    steps:
      - name: Noop
        if: false
        run: echo "This is a dummy step that will never run."

  setup-cross-build:
    name: "Determine Cross-build Targets"
    runs-on: ubuntu-24.04-arm
    needs: setup
    outputs:
      targets: ${{ steps.determine-targets.outputs.targets }}
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Build Package Tool
        run: cargo --color always build --release -p package
      - name: Upload package binary
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: |
            target/release/package
            .gitignore
      - name: Determine Targets
        id: determine-targets
        run: echo targets="$(target/release/package --print-targets json)" >> "$GITHUB_OUTPUT"

  cross-build:
    name: "Cross-build pexrc"
    needs: setup-cross-build
    runs-on: ubuntu-24.04-arm
    # N.B.: We break these up just to save wall time; they all can be built on 1 machine in ~40
    # minutes; this gets us to a ~12 minute long-pole.
    strategy:
      matrix:
        target: ${{ fromJSON(needs.setup-cross-build.outputs.targets) }}
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - name: Download package binary
        uses: actions/download-artifact@v7
        with:
          name: package
      - name: Build pexrc binary for all targets.
        run: |
          chmod +x target/release/package
          export CARGO="$(command -v cargo)"
          target/release/package \
            --color always --profile release -o dist --target ${{ matrix.target }}
      - name: Upload pexrc artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}
          path: |
            dist/pexrc*
            .gitignore

  determine-tag:
    name: Determine the release tag to operate against.
    needs: setup
    runs-on: ubuntu-slim
    outputs:
      release-tag: ${{ steps.determine-tag.outputs.release-tag }}
      release-version: ${{ steps.determine-tag.outputs.release-version }}
    steps:
      - name: Determine Tag
        id: determine-tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            RELEASE_TAG=${{ github.event.inputs.tag }}
          else
            RELEASE_TAG=${GITHUB_REF#refs/tags/}
          fi
          if [[ "${RELEASE_TAG}" =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            echo "release-tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
            echo "release-version=${RELEASE_TAG#v}" >> $GITHUB_OUTPUT
          else
            echo "::error::Release tag '${RELEASE_TAG}' must match 'v\d+.\d+.\d+'."
            exit 1
          fi

  github-release:
    name: "Create Github Release"
    needs:
      - cross-build
      - determine-tag
    runs-on: ubuntu-24.04-arm
    environment: Release
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
      discussions: write
    steps:
      - name: Checkout Pexrc
        uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Generate Release Hashes Manifest.
        run: uv run dev-cmd --color always generate-release-hashes -- -i dist -o dist/hashes.md
      - name: Generate pexrc ${{ needs.determine-tag.outputs.release-tag }} artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: dist/pexrc*
      - name: Prepare Changelog
        id: prepare-changelog
        uses: a-scie/actions/changelog@v1.6
        with:
          changelog-file: ${{ github.workspace }}/CHANGES.md
          version: ${{ needs.determine-tag.outputs.release-version }}
      - name: Append Hashes to Changelog
        run: |
          changelog_tmp="$(mktemp)"
          cat "${{ steps.prepare-changelog.outputs.changelog-file }}" <(echo '***') dist/hashes.md \
            > "${changelog_tmp}"
          mv "${changelog_tmp}" "${{ steps.prepare-changelog.outputs.changelog-file }}"
      - name: Create ${{ needs.determine-tag.outputs.release-tag }} Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.determine-tag.outputs.release-tag }}
          name: pexrc ${{ needs.determine-tag.outputs.release-version }}
          body_path: ${{ steps.prepare-changelog.outputs.changelog-file }}
          draft: false
          prerelease: false
          files: dist/pexrc*
          fail_on_unmatched_files: true
          discussion_category_name: Announcements